[project]
name = "football-player-detection"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=7.1.0",
    "jupyter>=1.1.1",
    "jupyterlab>=4.4.10",
    "lap>=0.5.12",
    "numpy>=2.3.4",
    "opencv-python>=4.11.0.86",
    "pandas>=2.3.3",
    "ruff>=0.14.4",
    "scikit-learn>=1.8.0",
    "supervision>=0.27.0",
    "torch>=2.9.0",
    "ultralytics>=8.3.227",
    "wandb>=0.22.3",
]
